
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "-q0-", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: sh -c "npm run dev -- --host 0.0.0.0 --port 3000"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:5000
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
